// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBghTKrW-Y20lVXI4AUI3abveAKjWuZwsI',
    appId: '1:156632749397:web:390b90b6fed498e82a0bdc',
    messagingSenderId: '156632749397',
    projectId: 'steamproject-9476e',
    authDomain: 'steamproject-9476e.firebaseapp.com',
    storageBucket: 'steamproject-9476e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2FQcavkrAf6zPHGFUCSvp-IhYHcZ0VgI',
    appId: '1:156632749397:android:ddb3105e8e0595732a0bdc',
    messagingSenderId: '156632749397',
    projectId: 'steamproject-9476e',
    storageBucket: 'steamproject-9476e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSf63nmwS0C5V_217ZFFanWjQc4uAknJU',
    appId: '1:156632749397:ios:bd8fa5ffcc5b0f8c2a0bdc',
    messagingSenderId: '156632749397',
    projectId: 'steamproject-9476e',
    storageBucket: 'steamproject-9476e.appspot.com',
    iosClientId: '156632749397-j3e6iia4891b1bqvc4p97aolob1f2o7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.steamproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSf63nmwS0C5V_217ZFFanWjQc4uAknJU',
    appId: '1:156632749397:ios:bd8fa5ffcc5b0f8c2a0bdc',
    messagingSenderId: '156632749397',
    projectId: 'steamproject-9476e',
    storageBucket: 'steamproject-9476e.appspot.com',
    iosClientId: '156632749397-j3e6iia4891b1bqvc4p97aolob1f2o7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.steamproject',
  );
}
